### ISSUE TITLE
Integrate recipients management into phoenix API

### ISSUE THREAD

**Issue by dwtong** [dwtong/kaibosh#2]
## Tasks
- [x] Show recipient with contact details
- [x] Toggle onboarding checklist items for recipient
- [x] Create new recipient
- [x] Update existing recipient
- [x] Archive recipient
- [x] Generate recipient's status
- [x] List recipients with bases and statuses
