### ISSUE TITLE
Add additional validation to sessions and holds

### ISSUE THREAD

**Issue by dwtong** [dwtong/kaibosh#30]
## Tasks
- [ ] Hold start date must be before end date
  - [ ] API
  - [ ] Web
- [ ] Hold must have at least one session
  - [ ] API
  - [ ] Web
- [ ] Session must have at least one allocation
  - [ ] API
  - [ ] Web
